"use strict";

exports.expected_trie = {"a":{"b":{"c":{".":["t1","t20"]},"b":{"c":{".":["t4"]},".":["t14"]},".":["t15"]},"*":{"c":{".":["t2"]},".":["t9"]},"#":{"b":{".":["t3"]},".":["t11"],"#":{".":["t12"]}}},"#":{".":["t5"],"#":{".":["t6"],"#":{".":["t24"]}},"b":{".":["t7"],"#":{".":["t26"]}},"*":{"#":{".":["t22"]}}},"*":{"*":{".":["t8"],"*":{".":["t18"]}},"b":{"c":{".":["t10"]}},"#":{".":["t21"],"#":{".":["t23"]}},".":["t25"]},"b":{"b":{"c":{".":["t13"]}},"c":{".":["t16"]}},"":{".":["t17"]},"vodka":{"martini":{".":["t19"]}}};

exports.expected_visits = [
    { type: 'start_entries' },
    { type: 'entry', key: 'a' },
    { type: 'start_entries' },
    { type: 'entry', key: 'b' },
    { type: 'start_entries' },
    { type: 'entry', key: 'c' },
    { type: 'start_entries' },
    { type: 'entry', key: '.' },
    { type: 'start_values' },
    { type: 'value', value: 't1' },
    { type: 'value', value: 't20' },
    { type: 'end_values' },
    { type: 'end_entries' },
    { type: 'entry', key: 'b' },
    { type: 'start_entries' },
    { type: 'entry', key: 'c' },
    { type: 'start_entries' },
    { type: 'entry', key: '.' },
    { type: 'start_values' },
    { type: 'value', value: 't4' },
    { type: 'end_values' },
    { type: 'end_entries' },
    { type: 'entry', key: '.' },
    { type: 'start_values' },
    { type: 'value', value: 't14' },
    { type: 'end_values' },
    { type: 'end_entries' },
    { type: 'entry', key: '.' },
    { type: 'start_values' },
    { type: 'value', value: 't15' },
    { type: 'end_values' },
    { type: 'end_entries' },
    { type: 'entry', key: '*' },
    { type: 'start_entries' },
    { type: 'entry', key: 'c' },
    { type: 'start_entries' },
    { type: 'entry', key: '.' },
    { type: 'start_values' },
    { type: 'value', value: 't2' },
    { type: 'end_values' },
    { type: 'end_entries' },
    { type: 'entry', key: '.' },
    { type: 'start_values' },
    { type: 'value', value: 't9' },
    { type: 'end_values' },
    { type: 'end_entries' },
    { type: 'entry', key: '#' },
    { type: 'start_entries' },
    { type: 'entry', key: 'b' },
    { type: 'start_entries' },
    { type: 'entry', key: '.' },
    { type: 'start_values' },
    { type: 'value', value: 't3' },
    { type: 'end_values' },
    { type: 'end_entries' },
    { type: 'entry', key: '.' },
    { type: 'start_values' },
    { type: 'value', value: 't11' },
    { type: 'end_values' },
    { type: 'entry', key: '#' },
    { type: 'start_entries' },
    { type: 'entry', key: '.' },
    { type: 'start_values' },
    { type: 'value', value: 't12' },
    { type: 'end_values' },
    { type: 'end_entries' },
    { type: 'end_entries' },
    { type: 'end_entries' },
    { type: 'entry', key: '#' },
    { type: 'start_entries' },
    { type: 'entry', key: '.' },
    { type: 'start_values' },
    { type: 'value', value: 't5' },
    { type: 'end_values' },
    { type: 'entry', key: '#' },
    { type: 'start_entries' },
    { type: 'entry', key: '.' },
    { type: 'start_values' },
    { type: 'value', value: 't6' },
    { type: 'end_values' },
    { type: 'entry', key: '#' },
    { type: 'start_entries' },
    { type: 'entry', key: '.' },
    { type: 'start_values' },
    { type: 'value', value: 't24' },
    { type: 'end_values' },
    { type: 'end_entries' },
    { type: 'end_entries' },
    { type: 'entry', key: 'b' },
    { type: 'start_entries' },
    { type: 'entry', key: '.' },
    { type: 'start_values' },
    { type: 'value', value: 't7' },
    { type: 'end_values' },
    { type: 'entry', key: '#' },
    { type: 'start_entries' },
    { type: 'entry', key: '.' },
    { type: 'start_values' },
    { type: 'value', value: 't26' },
    { type: 'end_values' },
    { type: 'end_entries' },
    { type: 'end_entries' },
    { type: 'entry', key: '*' },
    { type: 'start_entries' },
    { type: 'entry', key: '#' },
    { type: 'start_entries' },
    { type: 'entry', key: '.' },
    { type: 'start_values' },
    { type: 'value', value: 't22' },
    { type: 'end_values' },
    { type: 'end_entries' },
    { type: 'end_entries' },
    { type: 'end_entries' },
    { type: 'entry', key: '*' },
    { type: 'start_entries' },
    { type: 'entry', key: '*' },
    { type: 'start_entries' },
    { type: 'entry', key: '.' },
    { type: 'start_values' },
    { type: 'value', value: 't8' },
    { type: 'end_values' },
    { type: 'entry', key: '*' },
    { type: 'start_entries' },
    { type: 'entry', key: '.' },
    { type: 'start_values' },
    { type: 'value', value: 't18' },
    { type: 'end_values' },
    { type: 'end_entries' },
    { type: 'end_entries' },
    { type: 'entry', key: 'b' },
    { type: 'start_entries' },
    { type: 'entry', key: 'c' },
    { type: 'start_entries' },
    { type: 'entry', key: '.' },
    { type: 'start_values' },
    { type: 'value', value: 't10' },
    { type: 'end_values' },
    { type: 'end_entries' },
    { type: 'end_entries' },
    { type: 'entry', key: '#' },
    { type: 'start_entries' },
    { type: 'entry', key: '.' },
    { type: 'start_values' },
    { type: 'value', value: 't21' },
    { type: 'end_values' },
    { type: 'entry', key: '#' },
    { type: 'start_entries' },
    { type: 'entry', key: '.' },
    { type: 'start_values' },
    { type: 'value', value: 't23' },
    { type: 'end_values' },
    { type: 'end_entries' },
    { type: 'end_entries' },
    { type: 'entry', key: '.' },
    { type: 'start_values' },
    { type: 'value', value: 't25' },
    { type: 'end_values' },
    { type: 'end_entries' },
    { type: 'entry', key: 'b' },
    { type: 'start_entries' },
    { type: 'entry', key: 'b' },
    { type: 'start_entries' },
    { type: 'entry', key: 'c' },
    { type: 'start_entries' },
    { type: 'entry', key: '.' },
    { type: 'start_values' },
    { type: 'value', value: 't13' },
    { type: 'end_values' },
    { type: 'end_entries' },
    { type: 'end_entries' },
    { type: 'entry', key: 'c' },
    { type: 'start_entries' },
    { type: 'entry', key: '.' },
    { type: 'start_values' },
    { type: 'value', value: 't16' },
    { type: 'end_values' },
    { type: 'end_entries' },
    { type: 'end_entries' },
    { type: 'entry', key: '' },
    { type: 'start_entries' },
    { type: 'entry', key: '.' },
    { type: 'start_values' },
    { type: 'value', value: 't17' },
    { type: 'end_values' },
    { type: 'end_entries' },
    { type: 'entry', key: 'vodka' },
    { type: 'start_entries' },
    { type: 'entry', key: 'martini' },
    { type: 'start_entries' },
    { type: 'entry', key: '.' },
    { type: 'start_values' },
    { type: 'value', value: 't19' },
    { type: 'end_values' },
    { type: 'end_entries' },
    { type: 'end_entries' },
    { type: 'end_entries' }
];

exports.expected_true_visits = [
    { type: 'start_entries' },
    { type: 'entry', key: 'a' },
    { type: 'start_entries' },
    { type: 'entry', key: 'b' },
    { type: 'start_entries' },
    { type: 'entry', key: 'c' },
    { type: 'start_entries' },
    { type: 'entry', key: '.' },
    { type: 'start_values' },
    { type: 'value', value: true },
    { type: 'end_values' },
    { type: 'end_entries' },
    { type: 'entry', key: 'b' },
    { type: 'start_entries' },
    { type: 'entry', key: 'c' },
    { type: 'start_entries' },
    { type: 'entry', key: '.' },
    { type: 'start_values' },
    { type: 'value', value: true },
    { type: 'end_values' },
    { type: 'end_entries' },
    { type: 'entry', key: '.' },
    { type: 'start_values' },
    { type: 'value', value: true },
    { type: 'end_values' },
    { type: 'end_entries' },
    { type: 'entry', key: '.' },
    { type: 'start_values' },
    { type: 'value', value: true },
    { type: 'end_values' },
    { type: 'end_entries' },
    { type: 'entry', key: '*' },
    { type: 'start_entries' },
    { type: 'entry', key: 'c' },
    { type: 'start_entries' },
    { type: 'entry', key: '.' },
    { type: 'start_values' },
    { type: 'value', value: true },
    { type: 'end_values' },
    { type: 'end_entries' },
    { type: 'entry', key: '.' },
    { type: 'start_values' },
    { type: 'value', value: true },
    { type: 'end_values' },
    { type: 'end_entries' },
    { type: 'entry', key: '#' },
    { type: 'start_entries' },
    { type: 'entry', key: 'b' },
    { type: 'start_entries' },
    { type: 'entry', key: '.' },
    { type: 'start_values' },
    { type: 'value', value: true },
    { type: 'end_values' },
    { type: 'end_entries' },
    { type: 'entry', key: '.' },
    { type: 'start_values' },
    { type: 'value', value: true },
    { type: 'end_values' },
    { type: 'entry', key: '#' },
    { type: 'start_entries' },
    { type: 'entry', key: '.' },
    { type: 'start_values' },
    { type: 'value', value: true },
    { type: 'end_values' },
    { type: 'end_entries' },
    { type: 'end_entries' },
    { type: 'end_entries' },
    { type: 'entry', key: '#' },
    { type: 'start_entries' },
    { type: 'entry', key: '.' },
    { type: 'start_values' },
    { type: 'value', value: true },
    { type: 'end_values' },
    { type: 'entry', key: '#' },
    { type: 'start_entries' },
    { type: 'entry', key: '.' },
    { type: 'start_values' },
    { type: 'value', value: true },
    { type: 'end_values' },
    { type: 'entry', key: '#' },
    { type: 'start_entries' },
    { type: 'entry', key: '.' },
    { type: 'start_values' },
    { type: 'value', value: true },
    { type: 'end_values' },
    { type: 'end_entries' },
    { type: 'end_entries' },
    { type: 'entry', key: 'b' },
    { type: 'start_entries' },
    { type: 'entry', key: '.' },
    { type: 'start_values' },
    { type: 'value', value: true },
    { type: 'end_values' },
    { type: 'entry', key: '#' },
    { type: 'start_entries' },
    { type: 'entry', key: '.' },
    { type: 'start_values' },
    { type: 'value', value: true },
    { type: 'end_values' },
    { type: 'end_entries' },
    { type: 'end_entries' },
    { type: 'entry', key: '*' },
    { type: 'start_entries' },
    { type: 'entry', key: '#' },
    { type: 'start_entries' },
    { type: 'entry', key: '.' },
    { type: 'start_values' },
    { type: 'value', value: true },
    { type: 'end_values' },
    { type: 'end_entries' },
    { type: 'end_entries' },
    { type: 'end_entries' },
    { type: 'entry', key: '*' },
    { type: 'start_entries' },
    { type: 'entry', key: '*' },
    { type: 'start_entries' },
    { type: 'entry', key: '.' },
    { type: 'start_values' },
    { type: 'value', value: true },
    { type: 'end_values' },
    { type: 'entry', key: '*' },
    { type: 'start_entries' },
    { type: 'entry', key: '.' },
    { type: 'start_values' },
    { type: 'value', value: true },
    { type: 'end_values' },
    { type: 'end_entries' },
    { type: 'end_entries' },
    { type: 'entry', key: 'b' },
    { type: 'start_entries' },
    { type: 'entry', key: 'c' },
    { type: 'start_entries' },
    { type: 'entry', key: '.' },
    { type: 'start_values' },
    { type: 'value', value: true },
    { type: 'end_values' },
    { type: 'end_entries' },
    { type: 'end_entries' },
    { type: 'entry', key: '#' },
    { type: 'start_entries' },
    { type: 'entry', key: '.' },
    { type: 'start_values' },
    { type: 'value', value: true },
    { type: 'end_values' },
    { type: 'entry', key: '#' },
    { type: 'start_entries' },
    { type: 'entry', key: '.' },
    { type: 'start_values' },
    { type: 'value', value: true },
    { type: 'end_values' },
    { type: 'end_entries' },
    { type: 'end_entries' },
    { type: 'entry', key: '.' },
    { type: 'start_values' },
    { type: 'value', value: true },
    { type: 'end_values' },
    { type: 'end_entries' },
    { type: 'entry', key: 'b' },
    { type: 'start_entries' },
    { type: 'entry', key: 'b' },
    { type: 'start_entries' },
    { type: 'entry', key: 'c' },
    { type: 'start_entries' },
    { type: 'entry', key: '.' },
    { type: 'start_values' },
    { type: 'value', value: true },
    { type: 'end_values' },
    { type: 'end_entries' },
    { type: 'end_entries' },
    { type: 'entry', key: 'c' },
    { type: 'start_entries' },
    { type: 'entry', key: '.' },
    { type: 'start_values' },
    { type: 'value', value: true },
    { type: 'end_values' },
    { type: 'end_entries' },
    { type: 'end_entries' },
    { type: 'entry', key: '' },
    { type: 'start_entries' },
    { type: 'entry', key: '.' },
    { type: 'start_values' },
    { type: 'value', value: true },
    { type: 'end_values' },
    { type: 'end_entries' },
    { type: 'entry', key: 'vodka' },
    { type: 'start_entries' },
    { type: 'entry', key: 'martini' },
    { type: 'start_entries' },
    { type: 'entry', key: '.' },
    { type: 'start_values' },
    { type: 'value', value: true },
    { type: 'end_values' },
    { type: 'end_entries' },
    { type: 'end_entries' },
    { type: 'end_entries' }
];

if (Array.from === undefined)
{
	Array.from = function (s)
	{
		var a = [];
		s.forEach(function (v)
		{
			a[a.length] = v;
		});
		return a;
	};
}

function get_trie(matcher, t)
{
    t = t || matcher.get_trie();
    var k, r = {};
    for (k of t.keys())
    {
        if (k === '.')
        {
            r[k] = Array.from(t.get(k));
        }
        else
        {
            r[k] = get_trie(matcher, t.get(k));
        }
    }
    return r;
}

exports.get_trie = get_trie;

const util = require('util');

exports.ordered_sort = function (l)
{
    return [...l].sort((a, b) => {
        var ja = util.inspect(a, { sorted: true }),
            jb = util.inspect(b, { sorted: true });
        return ja < jb ? -1 : ja > jb ? 1 : 0;
    });
};
