dist: bionic
language: node_js
node_js:
  - 12
  - 13
env:
  - CXX=g++-9    
before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo add-apt-repository -y ppa:mhier/libboost-latest
  - sudo apt update
  - sudo apt -y install libboost1.70-dev g++-9
script:
  - if [ $TRAVIS_NODE_VERSION = 13 ]; then npm run coverage && npm run coveralls; else npm run test; fi
