dist: bionic
language: node_js
node_js:
  - 12
before_install:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test
  - sudo apt update
  - sudo apt install libboost-dev libboost-context-dev g++-9
  - g++ --version
script:
  - if [ $TRAVIS_NODE_VERSION = 12 ]; then npm run coverage; else npm run test; fi
