name: ci

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14, 16, 18]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Update APT
        run: sudo apt update

      - name: Install OS dependencies
        run: sudo apt install libboost-dev libboost-context-dev

      - name: Use Node ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install packages
        run: npm install

      - name: Lint
        run: npx grunt lint

      - name: Test
        if: matrix.node-version != '18'
        run: npm test

      - name: Coverage
        if: matrix.node-version == '18'
        run: npm run coverage

      - name: Coveralls
        if: matrix.node-version == '18'
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
